### ISSUE TITLE
Currently bundle is not compatible with Pimcore 11 

### ISSUE THREAD

**Issue by abrar123alhaq** [basilicom/pimcore-data-quality-bundle#10]
Currently bundle is not compatible with Pimcore 11

**Comment by ascheider** [comment]
I have the same question, will it be available for pimcore 11?

**Comment by AlexanderHeidrich** [comment]
We'll look into it asap!

**Comment by AlexanderHeidrich** [comment]
Pimcore 11 Support was added in Version 3.
